_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": val_spec
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": MIoU
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_dice
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_MIoU
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_dice
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_ppv
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_MIoU
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_ppv
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_spec
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": dice
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": spec
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ppv
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.9.15
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 48
                - 49
                - 53
                - 54
                - 55
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 48
                - 49
                - 53
                - 54
                - 55
                - 77
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.9.15
            "5": 0.19.11
            "6": 4.24.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
bert_type:
    value: StanfordAIMI/RadBERT
device:
    value: 0
feature_path:
    value: ../data
image_size:
    value:
        - 160
        - 256
        - 256
lr:
    value: 0.003
max_epochs:
    value: 300
meld_check:
    value: false
meld_script_path:
    value: ../meldgraph.sh
min_epochs:
    value: 20
model_save_filename:
    value: medseg
model_save_path:
    value: ./save_model
output_dir:
    value: ../data/output
patience:
    value: 20
project_dim:
    value: 768
project_name:
    value: FCD_detection
run_name:
    value: FCD_finetuning
test_csv_path:
    value: ../data/preprocessed/Res_full.csv
test_root_path:
    value: ../data/preprocessed
train_batch_size:
    value: 16
train_csv_path:
    value: ../data/preprocessed/Res_full.csv
train_root_path:
    value: ../data/preprocessed
valid_batch_size:
    value: 4
warmup_epochs:
    value: 0
