bert_type: StanfordAIMI/RadBERT
ckpt_path: ./save_model/exp1_no_gnn_full_aug
csv_path: ../data/preprocessed/MELD_BONN_full.csv
device: cpu
feature_dim:
- 32
- 32
- 64
- 64
- 128
- 128
- 256
feature_path: ../data
gnn_min_verts: 200000000
job_name: exp3_no_gnn_full
lr: 0.0003
max_epochs: 100
max_len: 256
meld_script_path: ../meldgraph.sh
min_epochs: 20
model_save_filename: medseg
model_save_path: ./save_model
num_unfreeze_layers: 0
output_dir: ../data/input
patience: 20
project_dim: 768
project_name: FCD_detection
run_name: FCD_finetuning
split_path: ../data/preprocessed/MELD_splits.csv
text_lens:
- 128
- 64
- 64
- 32
- 32
- 16
- 16
train_batch_size: 8
valid_batch_size: 4
