TRAIN:
  train_batch_size: 8
  lr              : 0.0003 # 0.003

  valid_batch_size: 4

  feature_dim     : [32, 32, 64, 64, 128, 128, 256]
  text_lens       : [128, 64, 64, 32, 32, 16, 16]
  max_len         : 256 # max text len

  min_epochs      : 20
  max_epochs      : 100
  warmup_epochs   : 0
  patience        : 20
  device          : 0

  model_save_path     : ./save_model
  model_save_filename : medseg

  project_name: FCD_detection
  run_name    : FCD_finetuning

MODEL:
  bert_type   : StanfordAIMI/RadBERT # Try: PubMedBERT, BioClinicalBERT
  project_dim : 768

  meld_script_path: ../meldgraph.sh
  feature_path    : ../data
  output_dir      : ../data/input

DATA:
  train_csv_path  : ../data/preprocessed/H101_reports_fullfull.csv # MELD_BONN_dataset_augmented_full.csv
  train_root_path : ../data/preprocessed/meld_files

  test_csv_path   : ../data/preprocessed/H101_reports_fullfull.csv # MELD_BONN_dataset_augmented_full.csv
  test_root_path  : ../data/preprocessed/meld_files

  split_path      : ../data/preprocessed/BONN_splits_full_test.csv