TRAIN:
  train_batch_size: 32
  lr: 0.0003

  valid_batch_size: 8

  image_size: [182, 218, 182] # [224,224]

  min_epochs: 20
  max_epochs: 100
  patience: 20

  device: 1

  model_save_path: ./save_model
  model_save_filename: medseg

MODEL:
  bert_type: microsoft/BiomedVLP-CXR-BERT-specialized
  vision_type: facebook/convnext-tiny-224
  project_dim: 768

  meld_script_path: ../meldgraph.sh
  feature_path: ../data
  output_dir: ../data/output

DATA:
  train_csv_path: ../data/preprocessed/NewFinal.csv # ./data/QaTa-COV19-v2/prompt/train.csv
  train_root_path: ../data/preprocessed # ./data/QaTa-COV19-v2/Train

  test_csv_path: ../data/preprocessed/NewFinal.csv #./data/QaTa-COV19-v2/prompt/test.csv
  test_root_path: ../data/preprocessed #./data/QaTa-COV19-v2/Test