_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.9.15
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 48
                - 49
                - 53
                - 54
                - 55
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 48
                - 49
                - 53
                - 54
                - 55
                - 77
                - 103
            "3":
                - 2
                - 7
                - 23
                - 55
                - 66
            "4": 3.9.15
            "5": 0.19.11
            "6": 4.24.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
